chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('<int:pk>', views.chatroom, name='chatroom'),
    path('ajax/<int:pk>/', views.ajax_load_messages, name='chatroom-ajax'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    reciver = models.ForeignKey(User, related_name='recived_messages', on_delete=models.CASCADE)
    message = models.TextField()
    seen = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

chat/views.py
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from .models import User, Message
from django.db.models import Q

import json


@ login_required
def chatroom(request, pk):
    other_user = get_object_or_404(User, pk=pk)
    messages = Message.objects.filter(
        Q(reciver=other_user, sender=request.user) | Q(reciver=request.user, sender=request.user)
    )
    messages.update(seen=True)
    return render(request, 'chatroom.html', {'other_user':other_user, 'messages':messages})


@ login_required
def ajax_load_messages(request, pk):
    other_user = get_object_or_404(User, pk=pk)
    messages = Message.objects.filter(seen=False)
    messages.update(seen=True)
    message_list = [{
        'sender': message.sender.username,
        'message': message.message,
        'sent': message.sender == request.user
        } for message in messages]
    if request.method == 'POST':
        message = json.loads(request.body)
        m = Message.objects.create(reciver=other_user, sender=request.user, message=message)
        message_list.append({
            'sender': request.user.username,
            'message': m.message,
            'sent':True,
        })
    return JsonResponse(message_list, safe=False)

templates/chatroom.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            box-sizing: border-box;
            padding: 0;
            margin: 0;
        }

        body {
            display: flex;
            height: 100vh;
            background: #666;
            flex-direction: column;
        }

        .header {
            padding: 10px 5%;
            background: #444;
            color: #888;
        }

        .messages-area {
            height: 100%;
            min-height: 70vh;
            overflow-y: auto;
            padding: 4%;
            background: #555;
            color: #999;
            padding-bottom: 10px;
        }

        .input-area {
            display: flex;
            flex-direction: row;
            justify-content: center;
        }

        #message-input {
            padding: 20px;
            width: 100%;
        }

        #send-btn {
            padding: 20px 40px;
            background: gold;
        }
        .message.left{
            text-align: left;
            color: #aaa;
        }
        .message.right {
            text-align: right;
            color: #ccc;
        }
        .message .content{
            background: #444;
            padding: 5px 10px;
            border-radius: 10px;
            max-width: 80%;
            display: inline-block;
        }

    </style>
</head>

<body>
    <div class="header">{{ other_user.username }}</div>
    <div class="messages-area">
        {% for message in messages %}
        <div class="message 
        {% if message.sender == request.user %}right{% else %}left{% endif %}
        ">
            <div class="sent-by">{{ message.sender.username }}</div>
            <div class="content">{{ message.message }}</div>
        </div>
        {% endfor %}
    </div>
    <div class="input-area">
        <input type="text" id="message-input">
        <button id="send-btn">Send</button>
    </div>
</body>
<script>
    let message_send_btn = document.getElementById("send-btn");
    let message_input = document.getElementById("message-input");
    function send_message() {
        let message = message_input.value;
        if (message === "") {
            return;
        }
        message_input.value = "";
        fetch("{% url 'chat:chatroom-ajax' other_user.id %}",
            {
                method: "POST",
                credentials: 'same-origin',
                headers: {
                    "Content-Type": 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify(message)
            }
        ).then(e => e.json()).then(messages => {
            for (message of messages) {
                construct_message(message);
            }
        });
    }

    function load_messages() {
        fetch("{% url 'chat:chatroom-ajax' other_user.id %}")
            .then(e => e.json())
            .then(messages => {
                console.log(messages)
                for (message of messages) {
                    construct_message(message);
                }
            })
    }

    function construct_message(message){
        let messages_container = document.querySelector(".messages-area");
        let class_name = "left"
        if (message.sent){
            class_name = "right"
        }
        let div = document.createElement("div");
        div.classList.add("message", class_name);
        div.innerHTML = `
        <div class="sent-by">${ message.sender }</div>
            <div class="content">${ message.message }</div>
        `
        messages_container.appendChild(div);
        div.scrollIntoView()
    }
    message_send_btn.addEventListener('click', send_message);
    setInterval(load_messages, 2000);
</script>


</html>